# Base image
FROM oven/bun:1-slim AS builder

# Set the working directory
WORKDIR /app

# Copy package.json and bun.lockb
COPY package.json bun.lock ./

# Install dependencies
RUN bun install

# Use a new, clean stage for the final image
FROM oven/bun:1-slim

# Set the working directory
WORKDIR /app

# Copy dependencies from the builder stage
COPY --from=builder /app/node_modules ./node_modules

# Copy the rest of the application code
COPY . .

ENV NODE_ENV=development

# Expose the port
ENV PORT=8000
EXPOSE 8000

# Run the application
CMD ["bun", "run", "dev"]
