# Stage 1: Build
FROM oven/bun:1-slim AS build
WORKDIR /app

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

COPY . .

# Build CSS + TS
RUN bun run build

# Stage 2: Runtime
FROM oven/bun:1-slim
WORKDIR /app

ENV NODE_ENV=production
ENV PORT=8000

# Copy ONLY what is needed to run
COPY --from=build /app/dist ./dist
COPY --from=build /app/public ./public

EXPOSE 8000

CMD ["bun", "dist/index.js"]
