services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    networks:
      - app-net
    env_file:
      - ./.env
    ports:
      - "${APP_PORT:-8888}:8000"
    depends_on:
      - minio
      - db
      - redis
    volumes:
      - ./:/app
      - app_node_modules:/app/node_modules
      - models_cache:/app/models
      - bun_cache:/root/.bun

  worker:
    build:
      context: ./worker-py
      dockerfile: Dockerfile
      target: ${WORKER_DEV_TARGET:-cpu-dev}
    restart: always
    networks:
      - app-net
    env_file:
      - ./.env
    depends_on:
      - minio
      - db
      - redis
    volumes:
      - ./worker-py:/app
      - worker_py_venv:/app/.venv
      - models_cache:/root/.cache/huggingface
    # gpus: all # optional, comment this if run on CPU-only machine

  minio:
    image: minio/minio
    restart: always
    networks:
      - app-net
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    volumes:
      - minio_data:/data

  redis:
    image: redis:alpine
    restart: always
    networks:
      - app-net
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  db:
    image: postgres:17-alpine
    restart: always
    networks:
      - app-net
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  minio_data:
  redis_data:
  postgres_data:
  bun_cache:
  models_cache:
  cargo_cache:
  app_node_modules:
  worker_py_venv:
networks:
  app-net:
    driver: bridge
