# Migration / Utility image
FROM oven/bun:1-slim

WORKDIR /app

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

COPY drizzle.config.ts ./
COPY src/db ./src/db
COPY src/utils ./src/utils

# default migrate
CMD ["bunx", "drizzle-kit", "push"]
